# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=http://localhost:5192

DELETE {{host}}/api/NonProduction
Content-Type: application/json
###
POST {{host}}/api/NonProduction
Content-Type: application/json
###
GET {{host}}/api/NonProduction?pswd=siiiiiiiiiiiifdnnnnnnnnnnn